### ISSUE TITLE
Erroneous output in chapter04_ex11

### ISSUE THREAD

**Issue by pithonsmear** [bewuethr/stroustrup_ppp#1]
I appreciate having this repo available as a resource as I'm working through the book.
This file, however, is just printing ```n_primes``` odd numbers, rather than ```n_primes``` first primes. It also skips 2.

Updated main, in case you care to update:
https://gist.github.com/pithonsmear/5477912532be67d1926271091214730c

**Comment by bewuethr** [comment]
Thanks for letting me know! I'll definitely update that.
