### ISSUE TITLE
Chapter 11 ex12 not reversing order

### ISSUE THREAD

**Issue by danvod** [bewuethr/stroustrup_ppp#3]
Hello and thank you for making this repository available to everyone.

I was going through exercises today and tried to solve the exercise 12 from chapter 11 on my own. I got pretty close and eventually wrote the same code as you did. Once that did not work, I tried your code and what happens is that the order of the characters in a new file is not reversed even though everything seems to be correct. Would you check that when you catch some time?

**Comment by bewuethr** [comment]
That's a difference between the first and second edition of the book. The first edition has only 15 exercises in Chapter 11, the second edition has 16. Exercise number 2 exists only in the second edition, and all exercise numbers after that are shifted by one.

This means: exercise 12 does what it's supposed to do, it reverses the order of *words*. To get reversed *characters*, you have to look at exercise 11.

Even though the numbering might be off, by reading the little comment blurb at the top of each solution, you should be able to figure out which exercise it is about. I'm not sure how many exercises were changed or re-numbered for the second edition.

**Comment by danvod** [comment]
You are right, I apologize for my silly mistake. Thank you once again.

**Comment by bewuethr** [comment]
No problem! Glad you find the repo useful.
