### ISSUE TITLE
chapter 13 ex 3 Arrow

### ISSUE THREAD

**Issue by ihavesomepoblem** [bewuethr/stroustrup_ppp#6]
How can you solve this task? What formulas or algorithms did you use?
(file: Graph.cpp, function:  Arrow::draw_lines()  )

**Comment by bewuethr** [comment]
Did you figure this one out? I'm literally drawing the lines of a triangle that make up an arrow head, I think with a size proportional to the total line length. I'd have to pull out a piece of paper to derive it again, though.

**Comment by ihavesomepoblem** [comment]
I try to figure it, but lack of geometric knowledge did not allow me to solve this task.
But in any case, thanks. I'll try to do this with help of trigonometric functions.
